
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Airplane : Luban.BeanBase
{
    public Airplane(JSONNode _buf) 
    {
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["asset_name"].IsString) { throw new SerializationException(); }  AssetName = _buf["asset_name"]; }
        { if(!_buf["gun_bind"].IsString) { throw new SerializationException(); }  GunBind = _buf["gun_bind"]; }
        { if(!_buf["gun"].IsString) { throw new SerializationException(); }  Gun = _buf["gun"]; }
        { if(!_buf["life"].IsNumber) { throw new SerializationException(); }  Life = _buf["life"]; }
        { if(!_buf["damage"].IsNumber) { throw new SerializationException(); }  Damage = _buf["damage"]; }
        { if(!_buf["speed_rate"].IsNumber) { throw new SerializationException(); }  SpeedRate = _buf["speed_rate"]; }
        { if(!_buf["Mass"].IsNumber) { throw new SerializationException(); }  Mass = _buf["Mass"]; }
        { if(!_buf["dampening"].IsNumber) { throw new SerializationException(); }  Dampening = _buf["dampening"]; }
        { if(!_buf["player_speed_rate"].IsNumber) { throw new SerializationException(); }  PlayerSpeedRate = _buf["player_speed_rate"]; }
        { if(!_buf["ammo"].IsString) { throw new SerializationException(); }  Ammo = _buf["ammo"]; }
        { var __json0 = _buf["dead_events"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; DeadEvents = new string[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  DeadEvents[__index0++] = __v0; }   }
    }

    public static Airplane DeserializeAirplane(JSONNode _buf)
    {
        return new Airplane(_buf);
    }

    public readonly string Id;
    public readonly string AssetName;
    public readonly string GunBind;
    public readonly string Gun;
    public readonly float Life;
    public readonly float Damage;
    /// <summary>
    /// 速率
    /// </summary>
    public readonly float SpeedRate;
    /// <summary>
    /// 质量
    /// </summary>
    public readonly float Mass;
    /// <summary>
    /// 反弹衰减
    /// </summary>
    public readonly float Dampening;
    public readonly float PlayerSpeedRate;
    public readonly string Ammo;
    public readonly string[] DeadEvents;
   
    public const int __ID__ = -612367502;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "assetName:" + AssetName + ","
        + "gunBind:" + GunBind + ","
        + "gun:" + Gun + ","
        + "life:" + Life + ","
        + "damage:" + Damage + ","
        + "speedRate:" + SpeedRate + ","
        + "Mass:" + Mass + ","
        + "dampening:" + Dampening + ","
        + "playerSpeedRate:" + PlayerSpeedRate + ","
        + "ammo:" + Ammo + ","
        + "deadEvents:" + Luban.StringUtil.CollectionToString(DeadEvents) + ","
        + "}";
    }
}

}

