
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Ammo : Luban.BeanBase
{
    public Ammo(JSONNode _buf) 
    {
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["asset_name"].IsString) { throw new SerializationException(); }  AssetName = _buf["asset_name"]; }
        { if(!_buf["life"].IsNumber) { throw new SerializationException(); }  Life = _buf["life"]; }
        { if(!_buf["damage"].IsNumber) { throw new SerializationException(); }  Damage = _buf["damage"]; }
        { if(!_buf["velocity"].IsNumber) { throw new SerializationException(); }  Velocity = _buf["velocity"]; }
        { if(!_buf["Mass"].IsNumber) { throw new SerializationException(); }  Mass = _buf["Mass"]; }
        { if(!_buf["dampening"].IsNumber) { throw new SerializationException(); }  Dampening = _buf["dampening"]; }
        { var __json0 = _buf["dead_trigger"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; DeadTrigger = new string[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  DeadTrigger[__index0++] = __v0; }   }
    }

    public static Ammo DeserializeAmmo(JSONNode _buf)
    {
        return new Ammo(_buf);
    }

    public readonly string Id;
    public readonly string AssetName;
    public readonly float Life;
    public readonly float Damage;
    /// <summary>
    /// 速度
    /// </summary>
    public readonly float Velocity;
    /// <summary>
    /// 质量
    /// </summary>
    public readonly float Mass;
    /// <summary>
    /// 反弹衰减
    /// </summary>
    public readonly float Dampening;
    public readonly string[] DeadTrigger;
   
    public const int __ID__ = 2044654;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "assetName:" + AssetName + ","
        + "life:" + Life + ","
        + "damage:" + Damage + ","
        + "velocity:" + Velocity + ","
        + "Mass:" + Mass + ","
        + "dampening:" + Dampening + ","
        + "deadTrigger:" + Luban.StringUtil.CollectionToString(DeadTrigger) + ","
        + "}";
    }
}

}

