
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Event : Luban.BeanBase
{
    public Event(JSONNode _buf) 
    {
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["asset_name"].IsString) { throw new SerializationException(); }  AssetName = _buf["asset_name"]; }
        { var __json0 = _buf["args"]; if(!__json0.IsArray) { throw new SerializationException(); } Args = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  Args.Add(__v0); }   }
    }

    public static Event DeserializeEvent(JSONNode _buf)
    {
        return new Event(_buf);
    }

    public readonly string Id;
    public readonly string AssetName;
    public readonly System.Collections.Generic.List<string> Args;
   
    public const int __ID__ = 67338874;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "assetName:" + AssetName + ","
        + "args:" + Luban.StringUtil.CollectionToString(Args) + ","
        + "}";
    }
}

}

