
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Reward : Luban.BeanBase
{
    public Reward(JSONNode _buf) 
    {
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["asset_name"].IsString) { throw new SerializationException(); }  AssetName = _buf["asset_name"]; }
        { if(!_buf["life"].IsNumber) { throw new SerializationException(); }  Life = _buf["life"]; }
        { if(!_buf["ammo_level"].IsNumber) { throw new SerializationException(); }  AmmoLevel = _buf["ammo_level"]; }
        { if(!_buf["speed_level"].IsNumber) { throw new SerializationException(); }  SpeedLevel = _buf["speed_level"]; }
        { if(!_buf["ammo_style"].IsString) { throw new SerializationException(); }  AmmoStyle = _buf["ammo_style"]; }
        { if(!_buf["duration"].IsNumber) { throw new SerializationException(); }  Duration = _buf["duration"]; }
    }

    public static Reward DeserializeReward(JSONNode _buf)
    {
        return new Reward(_buf);
    }

    public readonly string Id;
    public readonly string AssetName;
    public readonly float Life;
    public readonly int AmmoLevel;
    public readonly int SpeedLevel;
    public readonly string AmmoStyle;
    public readonly float Duration;
   
    public const int __ID__ = -1850459313;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "assetName:" + AssetName + ","
        + "life:" + Life + ","
        + "ammoLevel:" + AmmoLevel + ","
        + "speedLevel:" + SpeedLevel + ","
        + "ammoStyle:" + AmmoStyle + ","
        + "duration:" + Duration + ","
        + "}";
    }
}

}

