
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public TbAirplane TbAirplane {get; }
    public TbAmmo TbAmmo {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbAirplane = new TbAirplane(loader("tbairplane"));
        TbAmmo = new TbAmmo(loader("tbammo"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbAirplane.ResolveRef(this);
        TbAmmo.ResolveRef(this);
    }
}

}
