
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbAmmo
{
    private readonly System.Collections.Generic.Dictionary<string, Ammo> _dataMap;
    private readonly System.Collections.Generic.List<Ammo> _dataList;
    
    public TbAmmo(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, Ammo>();
        _dataList = new System.Collections.Generic.List<Ammo>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Ammo _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Ammo.DeserializeAmmo(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, Ammo> DataMap => _dataMap;
    public System.Collections.Generic.List<Ammo> DataList => _dataList;

    public Ammo GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Ammo Get(string key) => _dataMap[key];
    public Ammo this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

