
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbReward
{
    private readonly System.Collections.Generic.Dictionary<string, Reward> _dataMap;
    private readonly System.Collections.Generic.List<Reward> _dataList;
    
    public TbReward(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, Reward>();
        _dataList = new System.Collections.Generic.List<Reward>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Reward _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Reward.DeserializeReward(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, Reward> DataMap => _dataMap;
    public System.Collections.Generic.List<Reward> DataList => _dataList;

    public Reward GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Reward Get(string key) => _dataMap[key];
    public Reward this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

