
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbTrigger
{
    private readonly System.Collections.Generic.Dictionary<string, Trigger> _dataMap;
    private readonly System.Collections.Generic.List<Trigger> _dataList;
    
    public TbTrigger(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, Trigger>();
        _dataList = new System.Collections.Generic.List<Trigger>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Trigger _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Trigger.DeserializeTrigger(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, Trigger> DataMap => _dataMap;
    public System.Collections.Generic.List<Trigger> DataList => _dataList;

    public Trigger GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Trigger Get(string key) => _dataMap[key];
    public Trigger this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

