
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Trigger : Luban.BeanBase
{
    public Trigger(JSONNode _buf) 
    {
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["type"].IsString) { throw new SerializationException(); }  Type = _buf["type"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
    }

    public static Trigger DeserializeTrigger(JSONNode _buf)
    {
        return new Trigger(_buf);
    }

    public readonly string Id;
    public readonly string Type;
    public readonly string Name;
   
    public const int __ID__ = 604761496;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "type:" + Type + ","
        + "name:" + Name + ","
        + "}";
    }
}

}

